


apiVersion: apps/v1
kind: Deployment
metadata:
  name: cassandra-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cassandra-client
  template:
    metadata:
      labels:
        app: cassandra-client
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: main
        image: cassandra:latest
        imagePullPolicy: IfNotPresent