apiVersion: apps/v1
kind: Deployment
metadata:
  name: weatherstation
spec:
  replicas: 2
  selector:
    matchLabels:
      app: weatherstation
  template:
    metadata:
      labels:
        app: weatherstation
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: server
        image: gcr.io/megandemo/weatherstation:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080